name: giphy_app
description: A test of redux and flutter

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  redux: ^3.0.0
  redux_thunk: ^0.2.0
  redux_logging: ^0.3.0
  flutter_redux: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^3.0.0
  image_test_utils: ^1.0.0


flutter:
  uses-material-design: true
